telegram:
  bot_token: ""
  chat_id: 0

kafka:
  brokers:
    - "kafka:9092"
  topic: "site_alerts"
  group_id: "groupID"

redis:
  addr: "redis:6379"
  password: ""      
  db: 0         
  cooldown_minutes: 5  
  
